# Generated by Django 6.0.4 on 2026-04-26 11:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Material Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('unit', models.CharField(help_text='e.g. pc, kg, liter', max_length=50, verbose_name='Unit')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': 'Raw Materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact Person')),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='Rating from 0 to 5', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total Orders')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount')),
                ('delivery_days', models.PositiveIntegerField(default=0, verbose_name='Lead Time (days)')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_winner', models.BooleanField(default=False, verbose_name='Winner')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='purchasing.purchaserequest', verbose_name='Purchase Request')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='suppliers.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Price')),
                ('delivery_days', models.PositiveIntegerField(default=0, verbose_name='Lead Time (days)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.material', verbose_name='Material')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.quotation', verbose_name='Quotation')),
            ],
            options={
                'verbose_name': 'Quotation Item',
                'verbose_name_plural': 'Quotation Items',
            },
        ),
        migrations.CreateModel(
            name='SupplierMaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_price', models.DecimalField(blank=True, decimal_places=2, help_text='Reference price only, not final price', max_digits=12, null=True, verbose_name='Reference Price')),
                ('lead_time', models.PositiveIntegerField(default=0, verbose_name='Lead Time (days)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='suppliers.material', verbose_name='Material')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_prices', to='suppliers.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Material Price',
                'verbose_name_plural': 'Supplier Material Prices',
                'unique_together': {('supplier', 'material')},
            },
        ),
    ]
