# Generated by Django 6.0.4 on 2026-04-26 11:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantity')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.CharField(max_length=20, unique=True, verbose_name='Request Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('rfq_sent', 'RFQ Sent'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('awarded', 'Awarded')], default='draft', max_length=20, verbose_name='Status')),
                ('title', models.CharField(max_length=200, verbose_name='Request Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejection Date')),
                ('awarded_at', models.DateTimeField(blank=True, null=True, verbose_name='Award Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('email_error', models.TextField(blank=True, verbose_name='Email Error')),
            ],
            options={
                'verbose_name': 'RFQ Log',
                'verbose_name_plural': 'RFQ Logs',
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20, verbose_name='Action')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Action Date')),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Action By')),
            ],
            options={
                'verbose_name': 'Approval History',
                'verbose_name_plural': 'Approval Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
