# Generated by Django 6.0.4 on 2026-04-26 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchasing', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='awarded_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_requests', to='suppliers.supplier', verbose_name='Awarded Supplier'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Request Creator'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_requests', to=settings.AUTH_USER_MODEL, verbose_name='Rejected By'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaserequest', verbose_name='Purchase Request'),
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='purchasing.purchaserequest', verbose_name='Purchase Request'),
        ),
        migrations.AddField(
            model_name='rfqlog',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_logs', to='purchasing.purchaserequest', verbose_name='Purchase Request'),
        ),
        migrations.AddField(
            model_name='rfqlog',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_logs', to='suppliers.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='rfqlog',
            unique_together={('purchase_request', 'supplier')},
        ),
    ]
