# Generated by Django 6.0.4 on 2026-05-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_alter_approvalhistory_action_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalhistory',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('submit', 'Submit for Approval'), ('award', 'Award Supplier')], max_length=20, verbose_name='Action'),
        ),
    ]
