# Generated by Django 6.0.4 on 2026-05-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_approvalhistory_notes_alter_approvalhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='Priority'),
        ),
    ]
